org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# 發佈座標。實際發佈到 https://maven.pkg.github.com/leoho0722/LeoKit
GROUP=io.github.leoho0722
VERSION_NAME=0.1.0
