// LeoKit — 由 tokens/generate.mjs 產生，請勿手動編輯。
// 來源：tokens/tokens.json；要改 token 請改那裡，然後執行 `node tokens/generate.mjs`。

export const lkTokens = {
  color: {
    light: {
      'bg-canvas': '#f5f6f8',
      'bg-surface': '#ffffff',
      'bg-elevated': '#ffffff',
      'bg-subtle': '#eceef2',
      'bg-inset': '#e3e6eb',
      'bg-scrim': 'rgba(0, 0, 0, 0.4)',
      'bg-inverse': '#22262c',
      'text-primary': '#14171a',
      'text-secondary': '#4e555e',
      'text-tertiary': '#646c76',
      'text-disabled': '#a0a6ae',
      'text-on-brand': '#ffffff',
      'text-on-danger': '#ffffff',
      'text-on-inverse': '#f4f6f8',
      'brand': '#1e5fcc',
      'brand-hover': '#1a54b5',
      'brand-pressed': '#16489c',
      'brand-subtle': '#e8effc',
      'brand-ink': '#134391',
      'brand-on-inverse': '#8fb8ff',
      'success': '#1c7c4a',
      'success-subtle': '#e3f3e9',
      'success-ink': '#145f39',
      'warning': '#8a5a00',
      'warning-subtle': '#fbf0da',
      'warning-ink': '#6d4700',
      'danger': '#c22b2b',
      'danger-subtle': '#fce9e9',
      'danger-ink': '#9f1f1f',
      'text-link': '#1e5fcc',
      'border-subtle': '#e4e7ec',
      'border-default': '#d3d8df',
      'border-strong': '#aeb5bf',
      'border-control': '#7e858f',
      'border-focus': '#1e5fcc',
    },
    dark: {
      'bg-canvas': '#0e1116',
      'bg-surface': '#161a20',
      'bg-elevated': '#1d222a',
      'bg-subtle': '#232935',
      'bg-inset': '#0a0d11',
      'bg-scrim': 'rgba(0, 0, 0, 0.6)',
      'bg-inverse': '#e9ecf1',
      'text-primary': '#ebeef2',
      'text-secondary': '#a6aeb9',
      'text-tertiary': '#8a929e',
      'text-disabled': '#5c636d',
      'text-on-brand': '#08172e',
      'text-on-danger': '#2a0c0c',
      'text-on-inverse': '#14171a',
      'brand': '#5b9bff',
      'brand-hover': '#7aaeff',
      'brand-pressed': '#4a8aee',
      'brand-subtle': '#16243b',
      'brand-ink': '#a8c8ff',
      'brand-on-inverse': '#1e5fcc',
      'success': '#3fbf78',
      'success-subtle': '#112619',
      'success-ink': '#74d69d',
      'warning': '#e0a63c',
      'warning-subtle': '#2a2112',
      'warning-ink': '#f0c374',
      'danger': '#ff6b6b',
      'danger-subtle': '#2e1618',
      'danger-ink': '#ff9f9f',
      'text-link': '#5b9bff',
      'border-subtle': '#262c36',
      'border-default': '#333a45',
      'border-strong': '#4a525e',
      'border-control': '#737c88',
      'border-focus': '#5b9bff',
    },
  },
  spacing: {
    'spacing-0': '0',
    'spacing-2': '2px',
    'spacing-4': '4px',
    'spacing-8': '8px',
    'spacing-12': '12px',
    'spacing-16': '16px',
    'spacing-20': '20px',
    'spacing-24': '24px',
    'spacing-32': '32px',
    'spacing-40': '40px',
    'spacing-48': '48px',
    'spacing-64': '64px',
  },
  radius: {
    'radius-none': '0',
    'radius-xs': '4px',
    'radius-sm': '6px',
    'radius-md': '10px',
    'radius-lg': '14px',
    'radius-xl': '20px',
    'radius-2xl': '28px',
    'radius-pill': '999px',
  },
  size: {
    'control-h-sm': '32px',
    'control-h-md': '44px',
    'control-h-lg': '52px',
    'tap-min-ios': '44px',
    'tap-min-android': '48px',
    'icon-sm': '16px',
    'icon-md': '20px',
    'icon-lg': '24px',
    'icon-xl': '28px',
    'choice-size': '20px',
    'avatar-sm': '28px',
    'avatar-md': '36px',
    'avatar-lg': '48px',
    'track-h': '6px',
    'slider-thumb': '24px',
    'tabbar-h': '56px',
    'hairline': '1px',
    'border-w-strong': '1.5px',
    'focus-ring-w': '2px',
    'focus-ring-offset': '2px',
    'content-max': '720px',
    'layout-max': '1120px',
  },
  opacity: {
    'opacity-disabled': '0.4',
    'opacity-pressed': '0.72',
    'opacity-hover-layer': '0.06',
    'opacity-selected-layer': '0.12',
  },
  type: {
    'display': { fontSize: '34px', lineHeight: '40px', fontWeight: 700, family: 'display' },
    'title-1': { fontSize: '28px', lineHeight: '34px', fontWeight: 700, family: 'display' },
    'title-2': { fontSize: '22px', lineHeight: '28px', fontWeight: 600, family: 'display' },
    'title-3': { fontSize: '18px', lineHeight: '24px', fontWeight: 600, family: 'sans' },
    'headline': { fontSize: '16px', lineHeight: '22px', fontWeight: 600, family: 'sans' },
    'body': { fontSize: '16px', lineHeight: '24px', fontWeight: 400, family: 'sans' },
    'body-strong': { fontSize: '16px', lineHeight: '24px', fontWeight: 600, family: 'sans' },
    'callout': { fontSize: '15px', lineHeight: '22px', fontWeight: 400, family: 'sans' },
    'subhead': { fontSize: '14px', lineHeight: '20px', fontWeight: 500, family: 'sans' },
    'footnote': { fontSize: '13px', lineHeight: '18px', fontWeight: 400, family: 'sans' },
    'caption': { fontSize: '12px', lineHeight: '16px', fontWeight: 400, family: 'sans' },
    'label-lg': { fontSize: '16px', lineHeight: '20px', fontWeight: 600, family: 'sans' },
    'label': { fontSize: '14px', lineHeight: '16px', fontWeight: 600, family: 'sans' },
    'label-sm': { fontSize: '12px', lineHeight: '16px', fontWeight: 600, family: 'sans' },
    'code': { fontSize: '13px', lineHeight: '20px', fontWeight: 400, family: 'mono' },
  },
} as const;

export type LKTheme = keyof typeof lkTokens.color;
export type LKColorToken = keyof typeof lkTokens.color.light;
export type LKSpacingToken = keyof typeof lkTokens.spacing;
export type LKRadiusToken = keyof typeof lkTokens.radius;
export type LKSizeToken = keyof typeof lkTokens.size;
export type LKTypeStyle = keyof typeof lkTokens.type;
